version: "2.27"
services:
  main-api:
    build: ./main-api
    container_name: main-api
    command: sh -c "npm run start-test"

  auth-api:
    build: ./auth-api
    container_name: auth-api
    command: sh -c "npm run start-test"

  nextjs-app:
    build:
      context: ./nextjs-app
      args:
        NODE_ENV: test
    container_name: nextjs-app
    command: >
      sh -c "npx playwright install --with-deps && 
      npm run build:test && 
      npm run start && 
      wait"

  redis:
    image: redis:7.4.0
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
