version: "2.27"
services:
  main-api:
    build: ./main-api
    container_name: main-api
    ports:
      - '4000:4000'
    networks:
      - firetracker-network
    environment:
      - MONGO_URL=mongodb://mongo/firetracker
      - REDIS_HOST=redis
      - NEXTJS_APP_URL=http://nextjs-app:3000

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - '5000:5000'
    networks:
      - firetracker-network
    environment:
      - MONGO_URL=mongodb://mongo/firetracker
      - REDIS_HOST=redis
      - NEXTJS_APP_URL=http://nextjs-app:3000

  nextjs-app:
    build: ./nextjs-app
    container_name: nextjs-app
    ports:
      - '3001:3001'
    networks:
      - firetracker-network
    environment:
      - MAIN_API_URL=http://main-api:4000
      - AUTH_API_URL=http://auth-api:5000

  redis:
    image: redis:7.4.0
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - firetracker-network
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - firetracker-network
    volumes:
      - mongo-data:/data/db

networks:
  firetracker-network:
    driver: bridge


volumes:
  redis-data:
  redis-insight:
  mongo-data:
