version: "2.27"
services:
  api:
    build: ./api
    container_name: firetracker-api
    ports:
      - '4000:4000'
      - '5000:5000'
  app:
    build: ./app
    container_name: firetracker-app
    ports:
      - '3000:3000'
    environment:
      - MAIN_API_URL=http://api:4000
      - AUTH_API_URL=http://api:5000
    networks:
      - firetracker-network

networks:
  firetracker-network:
    driver: bridge