version: "2.27"
services:
  api:
    build: ./api
    container_name: firetracker-api
    ports:
      - '4000:4000'
      - '5000:5000'
    environment:
      - REDIS_HOST=redis

  app:
    build: ./app
    container_name: firetracker-app
    ports:
      - '3000:3000'
    environment:
      - MAIN_API_URL=http://api:4000
      - AUTH_API_URL=http://api:5000

  redis:
    image: redis:7.4.0
    container_name: firetracker-redis
    restart: always
    ports:
    - '6379:6379'
    volumes:
      - redis-data:/data

  redis_insight:
    image: redis/redisinsight:2.56
    container_name: firetracker-redis-insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

volumes:
  redis-data:
  redis-insight:
