version: "2.27"
services:
  api:
    build: ./api
    container_name: firetracker-api
    ports:
      - '4000:4000'
      - '5000:5000'
  frontend:
    build: ./frontend
    container_name: firetracker-frontend
    ports:
      - '3000:3000'
    environment:
      - AUTH_API_URL=http://api:5000
      - MAIN_API_URL=http://api:4000