version: "2.27"
services:
  main-api:
    build: ./main-api
    container_name: main-api
    ports:
      - '4000:4000'
    command: sh -c "npm run start"

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - '5000:5000'
    command: sh -c "npm run start"

  nextjs-app:
    build: ./nextjs-app
    container_name: nextjs-app
    ports:
      - '3000:3000'
    command: sh -c "npm run build && npm run start"

  redis:
    image: redis:7.4.0
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:
