name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Up Environment Variables
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" > backend/src/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> backend/src/.env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> backend/src/.env
          echo "AI_KEY=${{ secrets.AI_KEY }}" >> backend/src/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> backend/src/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> backend/src/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> backend/src/.env
          echo "NODE_API_URL=${{ secrets.NODE_API_URL }}" >> frontend/.env.local
          echo "NODE_AUTH_API_URL=${{ secrets.NODE_AUTH_API_URL }}" >> frontend/.env.local

      - name: Build Backend for testing
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: false
          load: true
          tags: firetracker-backend:test

      - name: Build Frontend for testing
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: false
          load: true
          tags: firetracker-frontend:test

      - name: Run Backend Tests
        run: |
          docker run --rm --env-file backend/src/.env firetracker-backend:test npm test

      - name: Run Frontend Tests
        run: |
          docker run --rm --env-file frontend/.env firetracker-frontend:test npm test

push-images:
  needs: build-and-test
  runs-on: ubuntu-latest
  if: github.event_name == 'push' && github.ref == 'refs/heads/main'

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/firetracker-backend:latest

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/firetracker-frontend:latest
