name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Up Environment Variables
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" > api/src/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> api/src/.env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> api/src/.env
          echo "AI_KEY=${{ secrets.AI_KEY }}" >> api/src/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> api/src/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> api/src/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> api/src/.env
          echo "MAIN_API_URL=${{ secrets.MAIN_API_URL }}" >> app/.env.local
          echo "AUTH_API_URL=${{ secrets.AUTH_API_URL }}" >> app/.env.local

      - name: Build api for testing
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: false
          load: true
          tags: firetracker-api:test

      - name: Build app for testing
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: false
          load: true
          tags: firetracker-app:test

      - name: Run api Tests
        run: |
          docker run --rm --env-file api/src/.env firetracker-api:test npm test

      - name: Run app Tests
        run: |
          docker run --rm --env-file app/.env.local firetracker-app:test npm test

  push-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/firetracker-api:latest

      - name: Build and push app
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/firetracker-app:latest
