name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Set Up Environment Variables
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" > backend/src/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> backend/src/.env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> backend/src/.env
          echo "AI_KEY=${{ secrets.AI_KEY }}" >> backend/src/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> backend/src/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> backend/src/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> backend/src/.env

      - name: Start Backend Server
        run: |
          cd backend/src
          node index &
          sleep 10s      # Wait for the server to be fully up

      - name: Run Tests
        run: |
          cd backend
          npm test

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Set Up Environment Variables
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" > backend/src/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> backend/src/.env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> backend/src/.env
          echo "AI_KEY=${{ secrets.AI_KEY }}" >> backend/src/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> backend/src/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> backend/src/.env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> backend/src/.env
          echo "NODE_API_URL=${{ secrets.NODE_API_URL }}" >> frontend/.env.local
          echo "NODE_AUTH_API_URL=${{ secrets.NODE_AUTH_API_URL }}" >> frontend/.env.local
          echo "IS_DEPLOYED=${{ secrets.IS_DEPLOYED }}" >> frontend/.env.local
          
      - name: Start Backend Server
        run: |
          cd backend/src
          node index &
          sleep 10s      # Wait for the server to be fully up

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Start app
        run: |
          cd frontend
          npm run start &
          sleep 10s     # Wait for the app to be fully up
          
      - name: Run Tests
        run: |
          cd frontend
          npx cypress run
