name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build services
        run: |
          docker compose -f docker-compose.test.yaml up --build -d

      - name: Wait Services To be Ready
        run: |
          sleep 30

      - name: Run auth api tests
        run: |
          docker exec -i auth-api npm test

      - name: Run main api tests
        run: |
          docker exec -i main-api npm test

      - name: Run App Tests
        run: |
          cd ${{ github.workspace }}/nextjs-app
          npm install
          npx playwright install --with-deps
          npm test
      
      - name: Upload trace artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-trace
          path: ${{ github.workspace }}/nextjs-app/test-results/
          include-hidden-files: true
          retention-days: 30
