name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set Up Environment Variables
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" > api/src/.env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> api/src/.env
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> api/src/.env
          echo "AI_KEY=${{ secrets.AI_KEY }}" >> api/src/.env
          echo "NODE_ENV=test" >> api/src/.env

      - name: Build
        run: |
          docker-compose up --build -d
              
      - name: Run API Tests
        run: |
          docker-compose exec -T api npm test

      - name: Run App Tests
        run: |
          docker-compose exec -T app npm test

      - name: Tear down services
        run: |
          docker-compose down 
